version: '3'

services :
    AserverHc : 
      container_name : AserverHc
      image : monitor
      build : ./
      restart : on-failure
      env_file :
        - .env
      volumes :
        - /var/run:/var/run/:ro   
      tty : true # since you used os.clear() to clear the ternminal you need to give the container a fake terminal to talk to
      

