name : monitoring_wk

on : push

jobs :
  one :
    runs-on: ubuntu-latest

    steps : 
      - name : repo_check
        uses : actions/checkout@v4
        
      - name : setup python 
        uses : actions/setup-python@v5
        with : 
          python-version : "3.12"
  

      - name : dependecies
        run : python -m pip install --upgrade pip && pip install -r requirements.txt

      - name : check_config
        run : cat ./setup/conf/usage.conf

      - name : running
        run :  |
                  python ./setup/script.py --ci &
                  echo $! > flask.pid                 # --ci run the other loop . avoid the endless while 
      - name : waiting
        run : sleep 5
      - name : check_logs
        run : cat ./setup/logs/docker.log && cat ./setup/logs/alerts.log
      - name : check_our_server
        run : curl http://localhost:5000
      - name : cleanup
        if   : always()
        run  : kill $(cat flask.pid)
        


  two : 
    needs : one
    runs-on: ubuntu-latest

    steps : 
      - name : repo_check2
        uses : actions/checkout@v4

      - name : build
        run : docker build -t monitor . # the git cloud computer has docker so no need to install it 
      - name : start
        run : docker run -d --name AserverHC --env-file .env  -p 5000:5000 monitor --ci 
      - name : waiting
        run : sleep 7
      - name: check_container
        run: docker ps -a
      - name: container_logs
        run: docker logs AserverHC
      - name : check
        run : curl http://localhost:5000
 
      - name : cleanup
        if   : always()
        run  : docker rm -f AserverHC


  three : 
    needs : two
    runs-on : ubuntu-latest

    steps : 
      - name : repo_check3
        uses : actions/checkout@v4
      - name : build
        run : docker compose build 
      - name : start 
        run : docker compose run -d --service-ports AserverHc  --ci
      - name : waiting
        run : sleep 7
      - name : check
        run : curl http://localhost:5000
      - name : cleanup
        if   : always()
        run  : docker compose rm -f AserverHc









